[jisike]
title = "지식채널e"
url = "https://jisike.ebs.co.kr/jisike/replayListNew"
entrySelector = "div.replay ul.list li"
titleSelector = "p.tit"
linkSelector = "div.vodmeta a"
contentSelector = "p.con"
imageSelector = "p.pic a img"
waitForSelector = "div.replay ul.list"
