[musicbank]
title = "뮤직뱅크 ─ 네이버 TV (API)"
url = "https://tv.naver.com/api/html/channel/musicbank/clips/1?order=recent"
entrySelector = "div.cds_area._infiniteCardArea div.cds._MM_CARD"
titleSelector = "dt.title a tooltip"
linkSelector = "a.cds_thm"
contentSelector = "span.tm_b"
imageSelector = "a.cds_thm img"
waitUntil = "networkidle"
timeout = 120
