[vogue_fashion]
title = "보그 코리아 ─ 패션"
url = "https://www.vogue.co.kr/category/fashion/"
entrySelector = "div.fusion-post-wrapper"
titleSelector = "h2.entry-title.fusion-post-title a"
linkSelector = "a"
dateSelector = "p > span:nth-child(3)"
dateFormat = "yyyy.mm-dd"
contentSelector = "span.fn a"
imageSelector = "img.attachment-full.size-full.wp-post-image"
waitUntil = "networkidle"
