[dc_taeyeon]
title = "태연갤러리 ─ 개념글"
url = "https://gall.dcinside.com/board/lists?id=taeyeon_new1&exception_mode=recommend"
entrySelector = "tr[data-type^='icon_recom']"
titleSelector = "td.gall_tit.ub-word a"
linkSelector = "td.gall_tit.ub-word > a:nth-child(1)"
