[vibe_onstage]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "div.section_intro"
titleSelector = "a.title"
linkSelector = "a.link_detail.scrollmagic.animated"
waitUntilSelector = ".section_intro"
