[ticket_csoon_hot]
title = "멜론티켓 ─ 티켓오픈소식 ─ HOT 공연 오픈 소식"
url = "https://ticket.melon.com/csoon/index.htm#orderType=0&pageIndex=1&schGcode=GENRE_ALL&schText=&schDt="
entrySelector = "ul.list_slider.list_hot_issue li div"
titleSelector = "strong.tit_consert"
linkSelector = "a.thumb_160x225"
contentSelector = "span.date"
imageSelector = "span.img > img"
waitUntil = "networkidle"
