[press]
title = "팩트체크넷 ─ 언론사"
url = "https://factchecker.or.kr/fc_archives/press"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.h5.text-base.font-medium.md:text-xl.uppercase.md:mt-2 > a"
linkSelector = "div.h5.text-base.font-medium.md:text-xl.uppercase.md:mt-2 > a"
contentSelector = "div.hidden.md:line-clamp-2.text-sm.text-gray-600.mt-2"
imageSelector = "div.flex-none.min-h-18.w-22.md:w-44.border-solid.border.bg-gray-100.md:-mt-4 > a > img"
waitUntil = "networkidle"
onFail = "stale"
