[ranking_popular]
title = "다음 뉴스 ─ 랭킹 ─ 많이 본"
url = "https://news.daum.net/ranking/popular"
entrySelector = "ul.list_news2 li"
titleSelector = "strong.tit_thumb"
linkSelector = "strong a.link_txt"
contentSelector = "span.info_news"
