[alookso_trend]
title = "alookso ─ 뜨는 글"
url = "https://alook.so/discover/trendiest"
entrySelector = "div.flex-auto.space-y-2"
titleSelector = "h5 a "
linkSelector = "h5 a "
contentSelector = "h6 a span"
waitUntil = "networkidle"
