[elle_fashion]
title = "엘르 코리아 ─ 패션"
url = "https://www.elle.co.kr/fashion"
entrySelector = "div.articlebox div.textbox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"
