[finance]
title = "블로터 ─ 금융"
url = "https://www.bloter.net/newsList/blt001005000"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
