[now_show_593_replay]
title = "네이버 나우. ─ 최강창민의 프리허그 ─ 다시보기"
url = "https://now.naver.com/show/593#replay"
entrySelector = "ul.episode_list.is_pc li.list_item"
titleSelector = "strong.title"
linkSelector = "*"
contentSelector = "div.sub_info"
waitForSelector = "ul.episode_list.is_pc li.list_item"
