[alookso_test]
title = "테스트"
url = "https://alook.so/users/8Ogtna"
entrySelector = "//section[1]/section/div/div"
titleSelector = "//div/h5/a"
linkSelector = "//div/h5/a"
contentSelector = "//div[2]/h6/a/div[@class='trix-content']"
dateSelector = "//div[1]/div/div/div[2]/div[@class='font-light text-gray-400 text-xxs']"
dateFormat = "yyyy.MM.dd."
waitUntil = "networkidle"
onFail = "stale"
