[ticket_online]
title = "인터파크 티켓 ─ 온라인"
url = "http://ticket.interpark.com/webzine/paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=1&KindOfGoods=TICKET&Genre=&sort=WriteDate&stext=%BF%C2%B6%F3%C0%CE"
entrySelector = "tbody tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td.date']"
waitUntil = "networkidle"
