[mbc_idol]
title = "iMBC 연예 ─ 아이돌"
url = "http://enews.imbc.com/ThemeIdol"
entrySelector = "ul.news-list.list-square.list-latest li"
titleSelector = "p.summary"
linkSelector = "a"
contentSelector = ""
imageSelector = "a img"
waitUntil = "networkidle"
