[smtown_news]
title = "SMTOWN â”€ Musicians News"
url = "https://www.smtown.com/artist/news/1"
entrySelector = "ul.search_news.artist li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a.class='btn_img.bg_cover"
contentSelector = "span.text"
