[pgr21]
title = "Pgr21 ─ 연예"
url = "https://ppt21.com/spoent/0?1=1&category=2"
entrySelector = "tbody tr[class='listtr']"
titleSelector = "td.tdsub.new a"
linkSelector = "td.tdsub.new a"
contentSelector = "td.tdname"
