[nestnada_inpock]
title = "네스트나다 ─ 인포크링크"
url = "https://link.inpock.co.kr/nestnada"
entrySelector = "a.link-a"
titleSelector = "div.link-meta p[class='inpock-typography paragraph-2 titleClass title']"
linkSelector = "a.link-a"
imageSelector = "div[class='link gtm-link-click-visitor'] div.image"
waitUntil = "networkidle"
