[yes24_ticket_exclusive]
title = "YES24 티켓 ─ 공지사항 (단독판매)"
url = "http://ticket.yes24.com/New/Notice/NoticeMain.aspx#list=Y&page=1"
entrySelector = "//html/body/div/div/div/div/table/tbody/tr"
titleSelector = "//td[2]/a[1]/em[2]"
linkSelector = "//td[2]/a[1]/em[2]"
contentSelector = "//td[3]"
waitUntil = "networkidle"
