[musinsa_magazine_news]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul.news-article-list.article-list.list li.listItem"
titleSelector = "p.title a"
linkSelector = "p.title a"
contentSelector = "div.description p"
imageSelector = "div.articleImg img"
waitForSelector = "ul.news-article-list.article-list.list li.listItem"
onFail = "stale"

[ssmuniverse_draw]
title = "스스므 ─ DRAW"
url = "https://ssmuniverse.com/board?category=12"
entrySelector = "div.exsi-item.grid.overflow-hidden a.card-item.grid-item.view-hidden"
titleSelector = "div.column-title.noto-h4.column-mb-15.text-break.text-overflow-3"
linkSelector = "a"
contentSelector = "div.column-content.noto-pr.mb-5.column-lineheight.w-100.text-break.text-overflow-5"
imageSelector = "img.column-img"
waitUntil = "networkidle"
onFail = "stale"
