[vibe_recent]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "div.section_intro div.video_info"
titleSelector = "a.title"
linkSelector = "div.main_text.custom_font.scrollmagic.animated a.title"
contentSelector = "p.desc"
waitUntil = "networkidle"
