[alookso_alookso]
title = "alookso â”€ alookso"
url = "https://alook.so/users/x4WtnB"
entrySelector = "//html/body/main/div[2]/div/div/section[1]/section/div/div"
titleSelector = "//div[2]/h5/a"
linkSelector = "//div[2]/h5/a"
contentSelector = "//div[2]/h6/a/div"
dateSelector = "//div[1]/div/div[2]/div[2]"
waitUntil = "networkidle"
