[independentfilm]
title = "독립영화관 ─ 네이버TV"
url = "https://tv.naver.com/kbs.independentfilm/clips"
entrySelector = "div.cds_area._infiniteCardArea div.cds._MM_CARD"
titleSelector = "dl.cds_info dt.title"
linkSelector = "div.cds_type a.cds_thm"
imageSelector = "div.cds_type a.cds_thm"
contentSelector = "span.tm_b"
waitForSelector = "div.cds_area._infiniteCardArea"
