[newstapa]
title = "뉴스타파"
url = "http://newstapa.org/recent"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.mm.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[%EA%B3%B5%EC%A7%81%EA%B0%90%EC%8B%9C]
title = "뉴스타파"
url = "http://newstapa.org/category/%EA%B3%B5%EC%A7%81%EA%B0%90%EC%8B%9C"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.mm.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"
