[entertain_news_music]
title = "다음 연예 ─ 뉴스 ─ 뮤직"
url = "https://entertain.daum.net/news/music"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "p.desc_thumb"
imageSelector = "img.thumb_g"
waitUntil = "networkidle"
