[alookso_test]
title = "테스트"
url = "https://alook.so/users/8Ogtna"
entrySelector = "//section[1]/section/div/div/div[@class='flex-auto mt-2 space-y-2']"
titleSelector = "//h5[1]/a[1]"
linkSelector = "//h5[1]/a[1]"
contentSelector = "//h6[1]/a[1]/div[1]"
waitUntil = "networkidle"
onFail = "stale"
matchAllof = "<h5"
