[kakaopage_sunwoohwang]
title = "카카오페이지 ─ 멋있으면 다 언니 황선우의 스압 인터뷰"
url = "https://page.kakao.com/home?seriesId=55414926"
entrySelector = "ul.css-14gr98z li"
titleSelector = "div.text-ellipsis.css-1mn7vax"
linkSelector = "div.jsx-922166243.imageWrapper"
dateSelector = "css-1o0fa02"
waitUntil = "networkidle"
