[independentfilm]
title = "독립영화관 ─ 네이버TV"
url = "https://tv.naver.com/kbs.independentfilm/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitForSelector = "div[class^='cds _MM_CARD']"
onFail = "stale"
