[privatecurve_notice]
title = "PRIVATE CURVE â”€ Notice"
url = "http://www.privatecurve.com/bbs/board.php?bo_table=news"
entrySelector = "div.total-sizing-wrap.grid div.gal-box.notice-box"
titleSelector = "h1.bold.line15"
linkSelector = "a"
contentSelector = "h2.ft14.col03"
imageSelector = "div.notice-images-box img"
waitUntil = "networkidle"
