[pgr21]
title = "Pgr21 ─ 연예"
url = "https://ppt21.com/spoent/0?1=1&category=2"
entrySelector = "tbody tr.listtr:not(tr.listnotice.listtr)"
titleSelector = "td.tdsub.new"
linkSelector = "td.tdsub.new"
contentSelector = "td.tdname"
waitUntil = "networkidle"
